name: Build

on: [push]



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Packages
        run: sudo apt-get install -y python3-pip python3-dev libpq-dev unixodbc-dev libsasl2-dev
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Pip Install
        run: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pip check
      - name: Tests
        run: pytest
      - name: Linting
        run: |
            flake8 --max-line-length=100
            isort ./client -c --diff
            isort ./follower_stats -c --diff
      - name: ping
        run: ping 192.241.142.192 -n 1
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: deploy code
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USER }}
  #       password: ${{ secrets.PASSWORD }}
  #       port: 22
  #       command_timeout: 200m
  #       script: whoami
  #       # script: |
  #       #   cd thepythongeek_new
  #       #   git pull
  #       #   docker-compose down
  #       #   docker-compose up
